library(ggplot2)
library(MASS)
library(nlme)
library(DBI)
library(sp)
library(raster)
library(maptools)
library(mgcv)
library(rgeos)
library(maps)
library(mapdata)
library(RMySQL)
library(rgdal)
library(gstat)
library(gdalUtils)
library(foreach)
library(doParallel)
library(readxl)
library(HousePC)

source('R/boundary.R',encoding = 'utf-8')
source('R/calLevel.R',encoding = 'utf-8')
source('R/calLevel2.R',encoding = 'utf-8')
source('R/calLevelPost.R',encoding = 'utf-8')
source('R/calLevelPost2.R',encoding = 'utf-8')
source('R/grid.R',encoding = 'utf-8')
source('R/hp_CHN.R',encoding = 'utf-8')
source('R/hp_CHNPost.R',encoding = 'utf-8')
source('R/hp_city.R',encoding = 'utf-8')
source('R/hp_cityPost.R',encoding = 'utf-8')
source('R/krig.R',encoding = 'utf-8')
source('R/preprocess.R',encoding = 'utf-8')
source('R/preprocess2.R',encoding = 'utf-8')
source('R/preprocessPost.R',encoding = 'utf-8')
source('R/preprocessPost2.R',encoding = 'utf-8')
source('R/prsp.R',encoding = 'utf-8')
source('R/readpr.R',encoding = 'utf-8')